name: Production Deployment

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.base_ref == 'staging'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Deploy to Production
        run: ./deploy_to_production.sh
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
