name: Staging Deployment

on:
  pull_request:
    branches:
      - staging

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.base_ref == 'dev'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Deploy to Staging
        run: ./deploy_to_staging.sh
        env:
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}
